# Generated by Django 4.1.4 on 2022-12-27 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_alter_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Task title')),
                ('description', models.CharField(max_length=512, verbose_name='Task description')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('TD', 'To Do'), ('DG', 'Doing'), ('D', 'Done')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.user')),
            ],
        ),
    ]
