version: '3'

services:
  backend:
    build:
      context: ./backend
    command: gunicorn utime.wsgi --bind 0.0.0.0:8002
    ports:
      - "8002:8002"
    depends_on:
      - db
  
  db:
    image: postgres:14.6-alpine
    volumes:
      - ./data/db:/var/lib/postgres/data

    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: postgres_db

  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend_build:/frontend/build/

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_build:/var/www/frontend/
    depends_on:
      - backend
      - frontend
volumes:
  frontend_build: